interface GeneratedCheckResult {
  isGenerated: boolean;
  reason?: 'path' | 'universal' | 'language-specific';
  matchedPattern?: string;
}

interface PathMatcher {
  description: string;
  matches: (parsedPath: string, fileName: string) => boolean;
}

const EXACT_FILENAMES = new Set([
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'Gemfile.lock',
  'Pipfile.lock',
  'composer.lock',
  'Cargo.lock',
  'poetry.lock',
  'go.sum',
  'go.mod',
  'pubspec.lock',
  'flake.lock',
  'Package.resolved',
  'packages.lock.json',
  '.terraform.lock.hcl',
  'bun.lockb',
  'gradle.lockfile',
  'uv.lock',
  'pdm.lock',
]);

const FILENAME_SUFFIXES = [
  '.min.js',
  '.min.css',
  '.bundle.js',
  '.bundle.css',
  '-min.js',
  '.map',
  '.pb.go',
  '.pb.rb',
  '.pb.py',
  '.pb.js',
  '.pb.cc',
  '.pb.h',
  '.pb2.py',
  '_pb2.py',
  '.grpc.pb.go',
  '_string.go',
  '.graphql.ts',
  '.graphql.js',
  '.openapi.ts',
  '.openapi.js',
  '.msw.ts',
  '.zod.ts',
  '.api.ts',
  '.g.dart',
  '.freezed.dart',
  '.g.cs',
  '.designer.cs',
  '_ide_helper.php',
] as const;

const ROOT_PATH_PREFIXES = ['vendor/', 'node_modules/', 'dist/', 'build/', 'out/'] as const;
const PATH_SEGMENTS = ['/generated/', '/gen/', '/__generated__/'] as const;

function matchesAnySuffix(fileName: string, suffixes: readonly string[]): boolean {
  return suffixes.some((suffix) => fileName.endsWith(suffix));
}

function isWordCharacter(char: string): boolean {
  const code = char.charCodeAt(0);
  return (
    (code >= 48 && code <= 57) ||
    (code >= 65 && code <= 90) ||
    (code >= 97 && code <= 122) ||
    code === 95
  );
}

function isWordString(text: string): boolean {
  if (text.length === 0) {
    return false;
  }

  for (const char of text) {
    if (!isWordCharacter(char)) {
      return false;
    }
  }

  return true;
}

function hasGeneratedSuffix(fileName: string, marker: '.generated.' | '.gen.'): boolean {
  const markerIndex = fileName.lastIndexOf(marker);
  if (markerIndex === -1) {
    return false;
  }

  return isWordString(fileName.slice(markerIndex + marker.length));
}

// Layer 1: Path/Filename Patterns
const PATH_MATCHERS: PathMatcher[] = [
  {
    description: 'exact-filename',
    matches: (_parsedPath, fileName) => EXACT_FILENAMES.has(fileName),
  },
  {
    description: 'minified-or-generated-suffix',
    matches: (_parsedPath, fileName) => matchesAnySuffix(fileName, FILENAME_SUFFIXES),
  },
  {
    description: 'generated-extension',
    matches: (_parsedPath, fileName) =>
      hasGeneratedSuffix(fileName, '.generated.') || hasGeneratedSuffix(fileName, '.gen.'),
  },
  {
    description: 'mockgen-go',
    matches: (_parsedPath, fileName) => fileName.startsWith('mock_') && fileName.endsWith('.go'),
  },
  {
    description: 'mocks-go-directory',
    matches: (parsedPath, fileName) => parsedPath.includes('mocks/') && fileName.endsWith('.go'),
  },
  {
    description: 'root-generated-directory',
    matches: (parsedPath) => ROOT_PATH_PREFIXES.some((prefix) => parsedPath.startsWith(prefix)),
  },
  {
    description: 'generated-path-segment',
    matches: (parsedPath) => PATH_SEGMENTS.some((segment) => parsedPath.includes(segment)),
  },
];

// Layer 2: Universal Header Patterns
const UNIVERSAL_PATTERNS: RegExp[] = [
  // Most common markers
  /@generated\b/,
  /\bDO NOT EDIT\b/i,
  /\bDO NOT MODIFY\b/i,
  /\bAUTO[- ]?GENERATED\b/i,
  /\bTHIS FILE IS GENERATED\b/i,
  /\bGENERATED CODE\b/i,
  /\bMACHINE GENERATED\b/i,

  // Common tool output phrases
  /Generated by\b/i,
  /Autogenerated by\b/i,
  /Created by .* - DO NOT EDIT/i,
  /This file was generated/i,
  /This is a generated file/i,

  // XML/HTML style
  /<auto-generated\s*\/?>/i,
  /<!-- Generated by/i,
];

// Layer 3: Language-Specific Patterns
interface LanguagePattern {
  extensions: string[];
  patterns: RegExp[];
}

const LANGUAGE_SPECIFIC: LanguagePattern[] = [
  {
    extensions: ['.go'],
    patterns: [
      // Go official specification (https://golang.org/s/generatedcode)
      /^\/\/ Code generated .* DO NOT EDIT\.$/m,
      /Code generated by protoc-gen-go/,
      /Code generated by Wire/,
      /Code generated by ent/,
      /Code generated by sqlc/,
      /Code generated by MockGen/,
      /Code generated by go-swagger/,
      /Code generated by "stringer"/,
    ],
  },
  {
    extensions: ['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs'],
    patterns: [
      /generated using openapi-typescript-codegen/i,
      /This file was auto-generated by openapi/i,
      /Generated by orval/i,
      /THIS FILE WAS GENERATED/,
      /Generated by graphql-codegen/i,
      /Prisma Client JS/,
      /Generated by the protocol buffer/,
      /GENERATED CODE -- DO NOT EDIT/,
      /@generated SignedSource/,
      /Generated by Apollo/,
    ],
  },
  {
    extensions: ['.rb'],
    patterns: [
      /This file is auto-generated from the current state of the database/,
      /This file is autogenerated/,
      /Generated by the protocol buffer/,
      /Autogenerated by Thrift/,
      /DO NOT MODIFY.*schema/i,
    ],
  },
  {
    extensions: ['.php'],
    patterns: [
      /This class was generated by/i,
      /Doctrine .* Generated/i,
      /Generated by the protocol buffer/,
      /auto-generated by Symfony/i,
    ],
  },
  {
    extensions: ['.py'],
    patterns: [
      /Generated by the protocol buffer compiler/,
      /@generated by mypy-protobuf/,
      /Generated by the gRPC/,
      /Autogenerated by Thrift/,
      /# Generated by Django/,
      /autogenerated by sqlacodegen/i,
      /generated by datamodel-codegen/,
    ],
  },
  {
    extensions: ['.java', '.kt'],
    patterns: [
      /Generated by the protocol buffer/,
      /@javax\.annotation\.Generated/,
      /@Generated\(/,
      /Generated by the gRPC/,
      /Generated by Dagger/,
      /generated at.*by JAXB/i,
      /OpenAPI Generator/,
    ],
  },
  {
    extensions: ['.cs'],
    patterns: [
      /<auto-generated>/,
      /<autogenerated>/,
      /Generated by the protocol buffer/,
      /auto-generated by EF/i,
      /This code was generated by a tool/,
    ],
  },
];

/**
 * Checks if a file is generated.
 * Uses a 3-layer approach:
 * 1. Path/Filename patterns (fastest, no reading)
 * 2. Universal header patterns (checks first 20 lines)
 * 3. Language-specific header patterns (checks first 20 lines)
 *
 * @param parsedPath The decoded git path of the file
 * @param getHeaderLines A function that lazily provides the first 20 lines of the file content
 */
export function isGeneratedFile(
  parsedPath: string,
  getHeaderLines?: () => string[],
): GeneratedCheckResult {
  // Layer 1: Path-based check (no file read)
  // We check if the filename matches any known generated patterns
  // or if the path is in a known generated directory
  const fileName = parsedPath.split('/').pop() || '';

  for (const matcher of PATH_MATCHERS) {
    if (matcher.matches(parsedPath, fileName)) {
      return {
        isGenerated: true,
        reason: 'path',
        matchedPattern: matcher.description,
      };
    }
  }

  // Optimization: Skip content checks for markdown files as they are documentation
  // and often contain examples of generated headers which trigger false positives.
  if (/\.(md|markdown)$/i.test(fileName)) {
    return { isGenerated: false };
  }

  // If no content provider is available, we can't check further
  if (!getHeaderLines) {
    return { isGenerated: false };
  }

  // Layer 2 & 3: Header-based check
  const lines = getHeaderLines();
  const header = lines.join('\n');

  // Universal patterns
  for (const pattern of UNIVERSAL_PATTERNS) {
    if (pattern.test(header)) {
      return {
        isGenerated: true,
        reason: 'universal',
        matchedPattern: pattern.source,
      };
    }
  }

  // Language-specific patterns
  // Simple extension extraction
  const extMatch = parsedPath.match(/\.[a-zA-Z0-9]+$/);
  const ext = extMatch ? extMatch[0] : '';

  const langPatterns = LANGUAGE_SPECIFIC.find((lang) => lang.extensions.includes(ext));

  if (langPatterns) {
    for (const pattern of langPatterns.patterns) {
      if (pattern.test(header)) {
        return {
          isGenerated: true,
          reason: 'language-specific',
          matchedPattern: pattern.source,
        };
      }
    }
  }

  return { isGenerated: false };
}
