packages:
  - .
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  lefthook: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - lefthook
